### ISSUE TITLE
Specify compatible concepticon version

### ISSUE THREAD

**Issue by martino-vic** [lingpy/pysen#12]
pysem works with concepticon v2.5.0 but not with the latest version. I think it would be nice to be able to see somewhere which concepticon version the [concepticon.zip file](https://github.com/lingpy/pysem/blob/master/src/pysem/data/concepticon.zip) is based on, e.g. in the readme. Or maybe the file could be updated by the latest version or even replaced by an API?

**Comment by xrotwang** [comment]
That's the problem of distributing data with a package. Since [concepticon has CLDF data](https://doi.org/10.5281/zenodo.7777658) now (and of reasonable size), I'd say referencing this data by DOI or version tag (and downloading/caching on-the-fly) would be the best option.

**Comment by LinguList** [comment]
I forgot to replace pysem with the most recent version.

**Comment by LinguList** [comment]
Normally, pysem follows the most recent concepticon version. This is still the case, I just haven't found time to do the release yet.

**Comment by LinguList** [comment]
For downloading and caching: this is surely a possibility, but maybe not for now, as this is not trivial (at least for me) to implement.

**Comment by LinguList** [comment]
The function to_concepticon now specifies the version. Pypi also specifies the version: https://pypi.org/project/pysem/

That should do the trick for now.

**Comment by martino-vic** [comment]
Thank you, awesome! Knowing the version is already a big win, and yeah, the API thing seems like a challenge
